Bump pkl.impl.ghactions to version 1.8.1

diff --git a/.github/workflows/prb.yml b/.github/workflows/prb.yml
--- a/.github/workflows/prb.yml
+++ b/.github/workflows/prb.yml
@@ -245,7 +245,7 @@ jobs:
         echo "pkl_exec=$PKL_EXEC" >> "$GITHUB_OUTPUT"
     - run: make pkl-format-lint
   verdict:
-    if: '!cancelled() && !failure()'
+    if: always()
     needs:
     - check-pkl-github-actions
     - test-pkl-0-25-3
@@ -259,7 +259,11 @@ jobs:
     - test-format-pkl
     runs-on: ubuntu-latest
     steps:
-    - run: 'true'
+    - name: Failure verdict
+      if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
+      run: |-
+        echo "Some of the required jobs are either failing or were cancelled"
+        exit 1
   upload-event-file:
     runs-on: ubuntu-latest
     steps:
